meta_product_name: "WeBet"
meta_title: "WeBet | Have fun with your friends!"
meta_description: "WeBet, helps you by letting you creating custom bets."
meta_image: "meta_image.png" # should exist in `app/assets/images/`
