meta_product_name: "WeBet"
meta_title: "WeBet - Have fun with your friends!"
meta_description: "WeBet, helps you have fun with your friends by creating custom bets."
meta_image: "landing_page.png" # should exist in `app/assets/images/`
